#!/bin/bash

INSTALL_DIR="/usr/local/bin"

gcc src/main.c src/line.c src/setup.c src/fileop.c -lncurses -o TextEditor

cp TextEditor "$INSTALL_DIR"

if ! grep -qxF "export PATH=\"$INSTALL_DIR:\$PATH\"" ~/.bashrc; then
  echo "export PATH=\"$INSTALL_DIR:\$PATH\"" >> ~/.bashrc
  source ~/.bashrc
fi
